### ISSUE TITLE
Fixed docker tag

### ISSUE THREAD

**Issue by kachkaev** [ianneub/docker-redirect#2]
Hi Ian and thank you for this image – really happy to discover it!
I prefer specifying the exact version in my `docker-compose.yml` to make sure that no BC problems emerge over time. Could you please create a fixed tag for what is now `latest`?

Cheers!

**Comment by ianneub** [comment]
Thank you for the suggestion @kachkaev ! This has been implemented. Sorry for such a long delay.

`docker pull ianneub/redirect:1.0` will now pull the specific `a4d27d781fcb711b05a59fa5078034263d49ca62` shasum version.
